### ISSUE TITLE
It seems reflections works against whole classpath

### ISSUE THREAD

**Issue by michaldo** [hosuaby/inject-resources#17]
I observe the following errors on my console - i think the reason is that reflections goes against whole classpath

15:37:28.554 [main] WARN org.reflections.Reflections - could not get type for name javax.servlet.jsp.JspWriter from any class loader
org.reflections.ReflectionsException: could not get type for name javax.servlet.jsp.JspWriter
	at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:312)
	at org.reflections.Reflections.expandSuperTypes(Reflections.java:382)
	at org.reflections.Reflections.<init>(Reflections.java:140)
	at com.adelean.inject.resources.junit.jupiter.core.TestsAdviceProcessor.findAdviceClass(TestsAdviceProcessor.java:38)

**Comment by hosuaby** [comment]
@michaldo which version do you use ? In version `0.3.0` I removed useless classpath scan.

**Comment by michaldo** [comment]
I use version 0.3.0
I use jupiter library in test and I think this line
https://github.com/hosuaby/inject-resources/blob/master/inject-resources-junit-jupiter/src/main/java/com/adelean/inject/resources/junit/jupiter/core/TestsAdviceProcessor.java#L38
starts reflection too high

**Comment by baibaichen** [comment]
@hosuaby 

Any idea for this issue? I also met this such issue.

**Comment by hosuaby** [comment]
Hello, 
I released version `0.3.1` which narrows classpath scan to the first three level of package. That means, if you test if located in the package `com.adelean.inject.resources.junit.jupiter.core` scan will only search for classes starting from `com.adelean.inject`.

**Comment by softmetz** [comment]
@hosuaby This change has broken the new version. 0.3.0 works. Interestingly a similar structured project with more classes/tests still work, but my almost empty project with only one class and test fails.

It fails with

```
org.reflections.ReflectionsException: Scanner SubTypesScanner was not configured

	at org.reflections.Store.get(Store.java:39)
	at org.reflections.Store.getAllIncluding(Store.java:75)
	at org.reflections.Reflections.getAllAnnotated(Reflections.java:469)
	at org.reflections.Reflections.getTypesAnnotatedWith(Reflections.java:430)
	at org.reflections.Reflections.getTypesAnnotatedWith(Reflections.java:416)
	at com.adelean.inject.resources.junit.jupiter.core.TestsAdviceProcessor.findAdviceClass(TestsAdviceProcessor.java:40)
	at com.adelean.inject.resources.junit.jupiter.TestWithResourcesExtension.beforeAll(TestWithResourcesExtension.java:47)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$10(ClassBasedTestDescriptor.java:381)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:381)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:205)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:80)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:148)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
```

**Comment by hosuaby** [comment]
@softmetz It is certainly must be related to package name. What is the name of package you test class belongs to ? If you can make a small repo to show the problem, that would be great.

**Comment by softmetz** [comment]
@hosuaby I created a small example at https://github.com/softmetz/demo-inject-resources-bug

I hope that will help you to figure out the problem. Thank you for looking into it.

**Comment by hosuaby** [comment]
I found the problem. It is due to to buggy version of `org.reflections`. If you force this dependency version to `0.10.2` test will pass:
```xml
<dependency>
      <groupId>org.reflections</groupId>
      <artifactId>reflections</artifactId>
      <version>0.10.2</version>
</dependency>
```

I will upgrade dependency in this project and make a new release ASAP.

**Comment by softmetz** [comment]
@hosuaby LGTM. Thank you!

**Comment by hosuaby** [comment]
`org.reflections` was upgraded in new release `0.3.2`.
